site_name: Nebula Container Orchestrator
theme: readthedocs
nav:
    - Home: index.md
    - Design:
      - Architecture: architecture.md
      - Internals: internals.md
    - Setting up:
      - Installing: 'installing/install.md'
      - Docker-compose localhost tutorial: 'installing/getting-started.md'
      - Globale cloud terraformed examples:
        - Digital Ocean: 'installing/digital-ocean-global-example.md'
        - Packet: 'installing/packet-global-example.md'
    - Configuring:
      - Using: use.md
      - Configuration settings:
        - 'config/apps.md'
        - 'config/device_groups.md'
        - 'config/manager.md'
        - 'config/worker.md'
        - 'config/reporter.md'
        - 'config/cron_jobs.md'
        - 'config/users.md'
        - 'config/user_groups.md'
      - Scaling: scaling.md
    - Controling:
      - CLI: cli.md
      - API:
        - General: 'api/general.md'
        - Apps: 'api/apps.md'
        - device_groups: 'api/device_groups.md'
        - users: 'api/users.md'
        - user_groups: 'api/user_groups.md'
        - cron_jobs: 'api/cron_jobs.md'
      - SDK:
        - Python: 'sdk/python.md'
    - Misc:
      - Automatically update workers: auto-update-workers.md
      - CI/CD:
          - Drone.io: 'ci-cd/drone.md'
          - Jenkins: 'ci-cd/jenkins.md'
      - Monitoring & Securing: best-practice.md
      - Nebula vs. Others: compare2orchestrators.md
      - Contributing: contribute.md
      - Where to get help: help.md
      - Release notes: release-notes.md
repo_url: https://github.com/nebula-orchestrator/docs
markdown_extensions:
  - admonition
